// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_drS2t0U12uU6RFWf0vmfkd8KKgcxpPk',
    appId: '1:950190301827:web:7c211908ab95eca4e031b6',
    messagingSenderId: '950190301827',
    projectId: 'sejeli',
    authDomain: 'sejeli.firebaseapp.com',
    storageBucket: 'sejeli.firebasestorage.app',
    measurementId: 'G-RTPN5RWWPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxq4JHRnmowVrXCX03Pq3F9j46jtJ20GU',
    appId: '1:950190301827:android:d79614fa8deba506e031b6',
    messagingSenderId: '950190301827',
    projectId: 'sejeli',
    storageBucket: 'sejeli.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGVmFOGY3jGakoyIfQJ-uGGKAXhol_UzA',
    appId: '1:950190301827:ios:600c92dc50a92d60e031b6',
    messagingSenderId: '950190301827',
    projectId: 'sejeli',
    storageBucket: 'sejeli.firebasestorage.app',
    iosBundleId: 'com.example.sejeli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGVmFOGY3jGakoyIfQJ-uGGKAXhol_UzA',
    appId: '1:950190301827:ios:600c92dc50a92d60e031b6',
    messagingSenderId: '950190301827',
    projectId: 'sejeli',
    storageBucket: 'sejeli.firebasestorage.app',
    iosBundleId: 'com.example.sejeli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_drS2t0U12uU6RFWf0vmfkd8KKgcxpPk',
    appId: '1:950190301827:web:15da51142c60f088e031b6',
    messagingSenderId: '950190301827',
    projectId: 'sejeli',
    authDomain: 'sejeli.firebaseapp.com',
    storageBucket: 'sejeli.firebasestorage.app',
    measurementId: 'G-MEMFLMSG1T',
  );
}
